<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto

namespace GPBMetadata;

class Demo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Api\Annotations::initOnce();
        $pool->internalAddGeneratedFile(
            '
Ç

demo.protoapi.helloworld.v1"
CreateDemoRequest"
CreateDemoReply"
UpdateDemoRequest"
UpdateDemoReply"
DeleteDemoRequest"
DeleteDemoReply"!
GetDemoRequest
user_id ("
GetDemoReply
result (	"
ListDemoRequest"
ListDemoReply2¡
DemoV

CreateDemo$.api.helloworld.v1.CreateDemoRequest".api.helloworld.v1.CreateDemoReplyV

UpdateDemo$.api.helloworld.v1.UpdateDemoRequest".api.helloworld.v1.UpdateDemoReplyV

DeleteDemo$.api.helloworld.v1.DeleteDemoRequest".api.helloworld.v1.DeleteDemoReply_
GetDemo!.api.helloworld.v1.GetDemoRequest.api.helloworld.v1.GetDemoReply"Ç”‰ì
/getDemoP
ListDemo".api.helloworld.v1.ListDemoRequest .api.helloworld.v1.ListDemoReplyB6
api.helloworld.v1PZhelloworld/api/helloworld/v1;v1bproto3'
        , true);

        static::$is_initialized = true;
    }
}

