<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: errors/errors.proto

namespace GPBMetadata\Errors;

class Errors
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
¢
errors/errors.protoerrors google/protobuf/descriptor.protoBY
com.github.kratos.errorsPZ,github.com/go-kratos/kratos/v2/errors;errors¢KratosErrorsbproto3'
        , true);

        static::$is_initialized = true;
    }
}

